---

secrets:
  bbb-test.opencast-niedersachsen.de:
    bigbluebutton: '{{ vault_bigbluebutton }}'
    greenlight: '{{ vault_greenlight }}'
    #sip:
    #  phone: '{{ vault_sip.phone }}'
    #  user: '{{ vault_sip.user }}'
    #  password: '{{ vault_sip.password }}'

container:
  greenlight:
    image: docker.io/bigbluebutton/greenlight
    tag: release-2.6.5
